[general]
import = ["~/.config/alacritty/colours.toml"]

[window]
opacity = 0.85
padding = { x = 10, y = 10 } 

[font]
normal = { family = "UbuntuMono Nerd Font", style = "bold" }
size = 16

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = { shape = "underline", blinking = "always" }
vi_mode_style = { shape = "underline", blinking = "always" }

unfocused_hollow = false
blink_timeout = 0
thickness = 0.3
